schema = {
    "covid_crawl_events" : [
        {"name": "_", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Country_Other", "type": "STRING", "mode": "NULLABLE"},
        {"name": "TotalCases", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "NewCases", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "TotalDeaths", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "NewDeaths", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "TotalRecovered", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "NewRecovered", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "ActiveCases", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Serious_Critical", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Tot_Cases_1M_pop", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Deaths_1M_pop", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "TotalTests", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Tests__1M_pop", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Population", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Continent", "type": "STRING", "mode": "NULLABLE"},
        {"name": "one_case_every_x_ppl", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "one_death_every_x_ppl", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "one_test_every_x_ppl", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "New_Cases_1M_pop", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "New_Deaths_1M_pop", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "Active_Cases_1M_pop", "type": "FLOAT64", "mode": "NULLABLE"},
        {"name": "last_updated_date", "type": "TIMESTAMP", "mode": "NULLABLE"},
    ]
}